const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const project = path.resolve(__dirname, '../..');
let app, temporary, page;
const errors = [];

(async () => {
  temporary = await fs.mkdtemp('/tmp/kursraum-reflections-ui-');
  const root = path.join(temporary, 'Kurse');
  const folder = path.join(root, 'Mein Kurs', '01 Einstieg');
  await fs.mkdir(folder, { recursive: true });
  await fs.writeFile(path.join(folder, '01 Lektion.txt'), 'Lektion über Dateien und Ordner.');
  const profile = path.join(temporary, 'profile');
  await fs.mkdir(profile);
  const settingsFile = path.join(profile, 'kursraum-settings.json');
  await fs.writeFile(settingsFile, JSON.stringify({ root, files: {}, chapters: {}, settings: { theme: 'dark' } }));
  const bootstrap = path.join(temporary, 'main.cjs');
  await fs.writeFile(bootstrap, `require('electron').app.setPath('userData', ${JSON.stringify(profile)});require(${JSON.stringify(path.join(project, 'electron/main.cjs'))});`);
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE; delete env.VITE_DEV_SERVER_URL;
  const launch = async () => {
    app = await electron.launch({ executablePath: path.join(project, 'node_modules/electron/dist/electron'), args: ['--no-sandbox', bootstrap], env });
    page = await app.firstWindow();
    page.on('pageerror', error => errors.push(error.message));
    await page.locator('.course-card').first().waitFor();
  };
  const button = name => page.getByRole('button', { name, exact: true });
  const fillPoints = async (one = 'Ich kann Dateien auflisten.', two = 'Ich kann Ordner anlegen.') => {
    await page.getByLabel('Lernpunkt 1', { exact: true }).fill(one);
    await page.getByLabel('Lernpunkt 2', { exact: true }).fill(two);
  };
  const save = async () => { await button('Speichern & abschließen').click(); await page.locator('.reflection-dialog').waitFor({ state: 'detached' }); };
  const states = () => page.evaluate(async () => {
    const overview = await window.kursraum.overview();
    const courseId = overview.courses[0].id;
    return window.kursraum.listFiles({ courseId, chapterPath: '01 Einstieg' });
  });
  await launch();
  // Record an actual short video using Chromium, without external codecs or fixtures.
  const bytes = await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 90;
    const context = canvas.getContext('2d');
    const stream = canvas.captureStream(10);
    const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp8' });
    const chunks = [];
    const done = new Promise(resolve => { recorder.ondataavailable = e => chunks.push(e.data); recorder.onstop = resolve; });
    recorder.start();
    let frame = 0;
    const draw = setInterval(() => { context.fillStyle = frame++ % 2 ? '#817ed5' : '#456a85'; context.fillRect(0, 0, 160, 90); }, 100);
    await new Promise(resolve => setTimeout(resolve, 700));
    recorder.stop(); await done; clearInterval(draw); stream.getTracks().forEach(track => track.stop());
    return [...new Uint8Array(await new Blob(chunks).arrayBuffer())];
  });
  await fs.writeFile(path.join(folder, '02 Video.webm'), Buffer.from(bytes));
  await fs.writeFile(path.join(folder, '03 Video.webm'), Buffer.from(bytes));
  await page.evaluate(() => window.kursraum.rescan());
  await page.locator('.course-card').first().click();
  await button('01 Lektion.txt ansehen').click();
  await button('Als gelesen').click();
  await page.locator('.reader-actions button.active').waitFor();
  assert.equal(await page.locator('.reflection-dialog').count(), 0);
  assert.equal((await states()).items[0].state.read, true);
  await button('Vorschau schließen').click();
  await button('Als abgeschlossen markieren').click();
  await button('Kapitel abgeschlossen').waitFor();
  assert.equal(await page.locator('.reflection-dialog').count(), 0);
  await button('Kapitel abgeschlossen').click();
  console.log('PASS: Documents and chapters complete immediately without a reflection prompt');

  await button('02 Video.webm ansehen').click();
  await button('Dateiinformationen').click();
  await button('Als gelesen').click();
  assert.equal(await button('Speichern & abschließen').isDisabled(), true);
  await fillPoints('Ein Punkt', '   ');
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('Eine mögliche Dienstleistung.');
  assert.equal(await button('Speichern & abschließen').isDisabled(), true);
  await fillPoints('Ein Punkt', ' ein punkt ');
  assert.equal(await button('Speichern & abschließen').isDisabled(), true);
  await fillPoints();
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('  ');
  assert.equal(await button('Speichern & abschließen').isDisabled(), true);
  await button('Noch nicht abschließen').click();
  assert.equal((await states()).items[1].state.read, false);
  await button('Dateiinformationen').click();
  console.log('PASS: Manual video completion requires two distinct points and a nonblank service idea');

  await button('Vollbild').click();
  await page.waitForFunction(() => Boolean(document.fullscreenElement));
  await page.locator('video').evaluate(video => video.play());
  await page.locator('.reflection-dialog').waitFor();
  assert.equal(await page.evaluate(() => Boolean(document.fullscreenElement)), false);
  await page.waitForTimeout(10500);
  assert.equal(await page.locator('.video-up-next').count(), 0);
  assert.equal((await states()).items[1].state.read, false);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.video-reader[open]').count(), 1);
  assert.equal(await page.locator('.video-up-next').count(), 0);
  await button('Video abschließen').click();
  await fillPoints();
  await button('Weiteren Lernpunkt hinzufügen').click();
  await page.getByLabel('Lernpunkt 3', { exact: true }).fill('Ich kann Pfade unterscheiden.');
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('Ich könnte eine Dateiablage für kleine Teams einrichten.');
  await page.getByLabel('Für wen? (optional)', { exact: true }).fill('Kleine Agenturen');
  await page.getByLabel('Erster Umsetzungsschritt (optional)', { exact: true }).fill('Eine Beispielablage bauen.');
  await page.screenshot({ path: path.join(temporary, 'reflection-dialog.png') });
  const previousSettings = await fs.readFile(settingsFile);
  await fs.unlink(settingsFile); await fs.mkdir(settingsFile);
  await button('Speichern & abschließen').click();
  await page.locator('.reflection-error').waitFor();
  assert.equal((await states()).items[1].state.read, false);
  assert.equal(await page.getByLabel('Für wen? (optional)', { exact: true }).inputValue(), 'Kleine Agenturen');
  await fs.rmdir(settingsFile); await fs.writeFile(settingsFile, previousSettings);
  await save();
  assert.equal((await states()).items[1].state.learningPoints.length, 3);
  assert.equal((await states()).items[1].state.serviceAudience, 'Kleine Agenturen');
  await page.locator('.video-countdown').waitFor();
  await button('Reflexion').click();
  assert.equal(await page.getByLabel('Lernpunkt 1', { exact: true }).inputValue(), 'Ich kann Dateien auflisten.');
  await button('Schließen').click();
  await page.getByText('Automatische Wiedergabe angehalten', { exact: true }).waitFor();
  await button('Jetzt abspielen').click();
  await page.locator('.reflection-dialog').waitFor();
  assert.equal(await page.getByLabel('Lernpunkt 1', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).inputValue(), '');
  await fillPoints('Letztes Video: Erster Punkt.', 'Letztes Video: Zweiter Punkt.');
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('Ich könnte einen Einführungsworkshop anbieten.');
  await save();
  await page.getByText('Du hast das letzte Video dieses Kurses erreicht.', { exact: true }).waitFor();
  await button('Dateiinformationen').click();
  await button('Gelesen').click();
  await button('Als gelesen').waitFor();
  assert.equal((await states()).items[2].state.read, false);
  assert.equal((await states()).items[2].state.serviceIdea, 'Ich könnte einen Einführungsworkshop anbieten.');
  await button('Vorschau schließen').click();
  console.log('PASS: Real fullscreen video end, blocked autoplay, extra points, save-error retry, next/final video and retained ideas');

  await button('Reflexion & Ideen').click();
  await page.locator('.reflection-card').nth(1).waitFor();
  assert.equal(await page.locator('.reflection-card').count(), 2);
  await page.getByRole('button', { name: /^Dienstleistungsideen/ }).click();
  await page.getByLabel('Reflexionen und Ideen durchsuchen').fill('Agenturen');
  assert.equal(await page.locator('.reflection-card').count(), 1);
  await page.getByLabel('Reflexionen nach Kurs filtern').selectOption({ label: 'Mein Kurs' });
  await button('Bearbeiten').click();
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('');
  assert.equal(await button('Änderungen speichern').isDisabled(), true);
  await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).fill('Ich könnte Dateiablagen planen und Teams bei der Einführung begleiten.');
  await page.getByLabel('Lernpunkt 3', { exact: true }).fill('Ich kann relative und absolute Pfade unterscheiden.');
  await button('Änderungen speichern').click();
  await page.locator('.reflection-dialog').waitFor({ state: 'detached' });
  await page.getByText('Lernpunkte zum Video ansehen', { exact: true }).click();
  assert.match(await page.locator('.reflection-card').innerText(), /relative und absolute Pfade/);
  await button('Video wieder ansehen').click();
  await button('Reflexion').click();
  assert.match(await page.getByLabel('Dienstleistungsidee (Pflichtfeld)', { exact: true }).inputValue(), /Einführung begleiten/);
  await button('Schließen').click();
  await button('Vorschau schließen').click();
  await page.getByLabel('Reflexionen und Ideen durchsuchen').fill('');
  await page.screenshot({ path: path.join(temporary, 'ideas-overview.png') });
  await page.getByRole('button', { name: /^Reflexionen / }).click();
  await page.screenshot({ path: path.join(temporary, 'reflections-overview.png') });
  console.log('PASS: Idea collection, search by audience, course filter, editing and video revisit');

  await page.evaluate(() => window.kursraum.setSetting('theme', 'light'));
  await app.close(); app = null;
  await launch();
  await button('Reflexion & Ideen').click();
  await page.locator('.reflection-card').nth(1).waitFor();
  assert.equal(await page.locator('.reflection-card').count(), 2);
  assert.match(await page.locator('.reflection-list').innerText(), /relative und absolute Pfade/);
  assert.match(await page.locator('.reflection-list').innerText(), /Einführung begleiten/);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(800, 650));
  await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 0);
  await page.screenshot({ path: path.join(temporary, 'reflections-light-small.png') });
  await page.locator('.reflection-card').first().getByRole('button', { name: 'Bearbeiten' }).click();
  await button('Änderungen speichern').scrollIntoViewIfNeeded();
  assert.equal(await button('Änderungen speichern').isVisible(), true);
  await page.screenshot({ path: path.join(temporary, 'reflection-small.png') });
  assert.deepEqual(errors, []);
  console.log('PASS: Restart persistence, light theme, small window, no renderer errors');
  console.log(`Screenshots: ${temporary}`);
})().catch(async error => { console.error(error); if (page && !page.isClosed()) await page.screenshot({ path: path.join(temporary, 'failure.png') }).catch(() => {}); process.exitCode = 1; }).finally(async () => {
  if (app) await app.close();
  // Keep screenshots and disposable profile in /tmp for inspection.
});
