const { _electron: electron } = require('playwright-core');
const assert=require('node:assert/strict'); const fs=require('node:fs/promises'); const path=require('node:path');
const project=path.resolve(__dirname,'../..');
let app,temporary; const errors=[];
(async()=>{
 temporary=await fs.mkdtemp('/tmp/kursraum-roadmap-ui-');const root=path.join(temporary,'Kurse');
 for(const name of ['01 Linux Grundlagen','02 Netzwerke','03 Server verwalten','04 Sicherheit']) {
  const dir=path.join(root,name);await fs.mkdir(path.join(dir,'01 Einstieg'),{recursive:true});await fs.mkdir(path.join(dir,'02 Praxis'));
  await fs.writeFile(path.join(dir,'01 Einstieg','Lektion.txt'),'Lernmaterial für '+name);await fs.writeFile(path.join(dir,'02 Praxis','Aufgabe.md'),'# Praxis\nEine Aufgabe.');
  await fs.copyFile(path.join(project,'example/Kurse/Linux Grundlagen/cover.jpg'),path.join(dir,'cover.jpg'));
 }
 const profile=path.join(temporary,'profile');await fs.mkdir(profile);await fs.writeFile(path.join(profile,'kursraum-settings.json'),JSON.stringify({root,files:{},chapters:{},settings:{theme:'dark',fontScale:1,locale:'de'}}));
 const bootstrap=path.join(temporary,'main.cjs');await fs.writeFile(bootstrap,`require('electron').app.setPath('userData',${JSON.stringify(profile)});require(${JSON.stringify(process.env.KURSRAUM_TEST_APP_MAIN || path.join(project,'electron/main.cjs'))});`);
 const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
 app=await electron.launch({executablePath:path.join(project,'node_modules/electron/dist/electron'),args:['--no-sandbox',bootstrap],env});
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await page.locator('.course-card').first().waitFor();
 await page.getByRole('button',{name:'Roadmaps',exact:true}).click();
 await page.getByRole('button',{name:'Neue Roadmap',exact:true}).click();
 await page.getByLabel('Name der Roadmap',{exact:true}).fill('Linux zum Serverprofi');
 for(const label of ['01 Linux Grundlagen','02 Netzwerke','03 Server verwalten','04 Sicherheit']) await page.locator('.roadmap-picker-list label').filter({hasText:label}).click();
 await fs.mkdir(path.join(project,'docs/roadmap'),{recursive:true});
 await page.screenshot({path:path.join(project,'docs/roadmap/01-erstellen.png')});
 await page.getByRole('button',{name:'Roadmap erstellen',exact:true}).click();
 await page.locator('.roadmap-node').first().waitFor();
 const mapId=await page.getByLabel('Roadmap auswählen',{exact:true}).inputValue();
 let record=await page.evaluate(id=>window.kursraum.roadmaps.get(id),mapId);assert.equal(record.nodes.length,4);
 console.log('PASS: Create via course picker');
 const cover=await page.evaluate(async()=>{const o=await window.kursraum.overview();const r=await fetch(window.kursraum.thumbnailUrl(o.courses[0].coverId));return (await createImageBitmap(await r.blob())).width;});assert.equal(cover,480);
 const firstId=record.nodes[0].id;const secondId=record.nodes[1].id;
 const first=page.locator(`.react-flow__node[data-id="${firstId}"]`);const second=page.locator(`.react-flow__node[data-id="${secondId}"]`);
 const source=await first.locator('.react-flow__handle-right').boundingBox();const target=await second.locator('.react-flow__handle-left').boundingBox();
 await page.mouse.move(source.x+source.width/2,source.y+source.height/2);await page.mouse.down();await page.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:15});await page.mouse.up();
 await page.waitForFunction(async id=>(await window.kursraum.roadmaps.get(id)).edges.length===1,mapId);
 const grip=await first.locator('.roadmap-node-grip').boundingBox();await page.mouse.move(grip.x+60,grip.y+10);await page.mouse.down();await page.mouse.move(grip.x+100,grip.y+65,{steps:12});await page.mouse.up();
 await page.waitForFunction(async ({id,node})=>(await window.kursraum.roadmaps.get(id)).nodes.find(n=>n.id===node).position.y>20,{id:mapId,node:firstId});
 await page.getByRole('button',{name:'Eigenschaften: 02 Netzwerke',exact:true}).click();
 await page.getByLabel('Lernziel',{exact:true}).fill('Netzwerke verstehen und sicher konfigurieren');
 await page.getByLabel('Dauer in Minuten',{exact:true}).fill('120');
 await page.getByLabel('Meilenstein',{exact:true}).check();
 await page.getByLabel('Folgekurs auswählen',{exact:true}).selectOption(record.nodes[2].id);
 await page.getByRole('button',{name:'Eigenschaften schließen',exact:true}).click();
 await page.waitForFunction(async id=>(await window.kursraum.roadmaps.get(id)).edges.length===2,mapId);
 await page.getByRole('button',{name:'Alles anzeigen',exact:true}).click();await page.waitForTimeout(400);
 await page.screenshot({path:path.join(project,'docs/roadmap/02-graph.png')});
 console.log('PASS: Drag connection, drag node, properties, edges persist');
 await first.getByRole('button',{name:'2 Kapitel',exact:true}).click();await first.locator('.roadmap-chapters button').first().waitFor();
 await first.locator('.roadmap-chapters button').filter({hasText:'02 Praxis'}).click();await page.locator('.chapter-heading h2').filter({hasText:'02 Praxis'}).waitFor();
 await page.getByRole('button',{name:'Roadmaps',exact:true}).click();await page.locator('.roadmap-node').first().waitFor();
 console.log('PASS: Expand chapters and open a specific chapter');
 await first.focus();await page.keyboard.press('Enter');
 await page.locator('.course-header h1').filter({hasText:'01 Linux Grundlagen'}).waitFor();
 await page.screenshot({path:path.join(project,'docs/roadmap/03-kurs-oeffnen.png')});
 await page.getByRole('button',{name:'Lektion.txt ansehen',exact:true}).click();
 await page.locator('.reader-actions').getByRole('button',{name:'Als gelesen',exact:true}).click();
 await page.getByRole('button',{name:'Vorschau schließen',exact:true}).click();
 await page.getByRole('button',{name:'Roadmaps',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.roadmap-node-progress')?.textContent.includes('50 %'));
 record=await page.evaluate(id=>window.kursraum.roadmaps.get(id),mapId);assert.equal(record.nodes[1].duration,120);
 console.log('PASS: Open course and live progress, return to saved graph');
 await page.getByRole('button',{name:'Pfad markieren',exact:true}).click();
 await page.getByRole('button',{name:'01 Linux Grundlagen öffnen',exact:true}).click();
 await page.getByRole('button',{name:'02 Netzwerke öffnen',exact:true}).click();
 await page.getByRole('button',{name:'Pfad starten',exact:true}).click();
 await page.getByRole('button',{name:'Nächster Kurs',exact:true}).click();await page.locator('.course-header h1').filter({hasText:'02 Netzwerke'}).waitFor();
 await page.getByRole('button',{name:'Zur Roadmap',exact:true}).click();
 await page.getByRole('checkbox',{name:'Weniger Effekte',exact:true}).check();await page.locator('.roadmap-page.reduced-effects').waitFor();
 // Exercise the real native-dialog import/export bridge with deterministic file selections.
 const exported=path.join(temporary,'roadmap.json');
 await app.evaluate(({dialog},filename)=>{dialog.showMessageBox=async()=>({response:0});dialog.showSaveDialog=async()=>({canceled:false,filePath:filename});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[filename]});},exported);
 await page.getByRole('button',{name:'Roadmap exportieren',exact:true}).click();
 await page.waitForTimeout(500);const exportedJson=JSON.parse(await fs.readFile(exported,'utf8'));assert.equal(exportedJson.format,'kursraum-roadmap');assert.ok(!JSON.stringify(exportedJson).includes(temporary));
 await page.getByRole('button',{name:'Importieren',exact:true}).click();
 await page.waitForFunction(async()=> (await window.kursraum.roadmaps.list()).length===2);
 await page.waitForFunction(id=>document.querySelector('[aria-label="Roadmap auswählen"]').value!==id,mapId);
 await page.locator('.roadmap-node').first().waitFor();
 await page.getByLabel('Roadmap umbenennen',{exact:true}).fill('Importierte Kopie');await page.getByRole('button',{name:'Roadmap speichern',exact:true}).click();
 await page.waitForFunction(async()=> (await window.kursraum.roadmaps.list()).some(m=>m.title==='Importierte Kopie'));
 const copyId=await page.getByLabel('Roadmap auswählen',{exact:true}).inputValue();
 assert.equal((await page.evaluate(id=>window.kursraum.roadmaps.get(id),copyId)).edges.length,2);
 await page.getByRole('button',{name:'Alles anzeigen',exact:true}).click();await page.waitForTimeout(350);
 const edgePath=page.locator('.react-flow__edge-path').first();const edgePoint=await edgePath.evaluate(e=>{const p=e.getPointAtLength(e.getTotalLength()/2);const t=new DOMPoint(p.x,p.y).matrixTransform(e.getScreenCTM());return {x:t.x,y:t.y};});
 await page.mouse.click(edgePoint.x,edgePoint.y);await page.getByRole('button',{name:'Verbindung entfernen',exact:true}).click();
 await page.waitForFunction(async id=>(await window.kursraum.roadmaps.get(id)).edges.length===1,copyId);
 await page.getByRole('button',{name:'Eigenschaften: 04 Sicherheit',exact:true}).click();await page.getByRole('button',{name:'Aus Roadmap entfernen',exact:true}).click();
 await page.waitForFunction(async id=>(await window.kursraum.roadmaps.get(id)).nodes.length===3,copyId);
 assert.equal((await page.evaluate(()=>window.kursraum.overview())).courses.length,4);
 await page.getByRole('button',{name:'Roadmap löschen',exact:true}).click();await page.getByRole('button',{name:'Endgültig löschen',exact:true}).click();
 await page.waitForFunction(async()=> (await window.kursraum.roadmaps.list()).length===1);
 console.log('PASS: Marked route, course sequence, reduced effects, JSON export/import/rename/delete');
 await page.getByLabel('Roadmap auswählen',{exact:true}).selectOption(mapId);await page.locator('.roadmap-node').first().waitFor();
 await page.evaluate(()=>window.kursraum.setSetting('theme','light'));await page.reload();
 await page.getByRole('button',{name:'Roadmaps',exact:true}).click();await page.getByLabel('Roadmap auswählen',{exact:true}).selectOption(mapId);await page.locator('.roadmap-node').first().waitFor();
 await page.getByRole('button',{name:'Alles anzeigen',exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:path.join(project,'docs/roadmap/04-hell.png')});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 assert.equal((await page.evaluate(id=>window.kursraum.roadmaps.get(id),mapId)).edges.length,2);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,700));await page.waitForTimeout(300);
 assert.ok(await page.locator('.roadmap-canvas').evaluate(e=>e.clientWidth>400 && e.clientHeight>200));
 await page.screenshot({path:path.join(project,'docs/roadmap/05-kleines-fenster.png')});
 assert.deepEqual(errors,[]);console.log('PASS: Reload persistence, light theme, small window; no renderer errors');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,900));
 for(let i=0;i<60;i++){const dir=path.join(root,`Performance ${String(i).padStart(2,'0')}`);await fs.mkdir(dir);await fs.writeFile(path.join(dir,'Lektion.txt'),'Test');}
 await page.evaluate(()=>window.kursraum.rescan());
 const perfId=await page.evaluate(async()=>{const o=await window.kursraum.overview();let r=await window.kursraum.roadmaps.create({title:'60 Lernstationen',courseIds:o.courses.filter(c=>c.name.startsWith('Performance ')).map(c=>c.id)});r=await window.kursraum.roadmaps.save({...r,nodes:r.nodes.map((n,i)=>({...n,position:{x:(i%10)*330,y:Math.floor(i/10)*300}}))});return r.id;});
 const begin=Date.now();await page.getByLabel('Roadmap auswählen',{exact:true}).selectOption(perfId);await page.locator('.roadmap-node').first().waitFor();
 await page.getByRole('button',{name:'Alles anzeigen',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.roadmap-node').length===60);const renderMs=Date.now()-begin;
 await page.evaluate(()=>{window.framesTest=[];let prev=performance.now();window.collectFrames=true;const sample=now=>{window.framesTest.push(now-prev);prev=now;if(window.collectFrames)requestAnimationFrame(sample);};requestAnimationFrame(sample);});
 const canvas=await page.locator('.roadmap-canvas').boundingBox();await page.mouse.move(canvas.x+50,canvas.y+30);await page.mouse.down();await page.mouse.move(canvas.x+180,canvas.y+100,{steps:40});await page.mouse.up();
 const frames=await page.evaluate(()=>{window.collectFrames=false;return window.framesTest;});frames.sort((a,b)=>a-b);const median=frames[Math.floor(frames.length/2)];
 assert.ok(renderMs<10000,`60-node render: ${renderMs}ms`);assert.ok(median<100,`Pan median frame: ${median}ms`);assert.ok(frames.length>5);
 console.log(`PASS: 60 nodes, render ${renderMs}ms, median pan frame ${median.toFixed(1)}ms`);
 await page.getByRole('button',{name:'Alles anzeigen',exact:true}).click();await page.screenshot({path:path.join(project,'docs/roadmap/06-sechzig-knoten.png')});
 await page.getByRole('button',{name:'Roadmap löschen',exact:true}).click();await page.getByRole('button',{name:'Endgültig löschen',exact:true}).click();await page.waitForFunction(async()=> (await window.kursraum.roadmaps.list()).length===1);
 assert.deepEqual(errors,[]);
 await app.close();app=null;
 const stored=JSON.parse(await fs.readFile(path.join(profile,'kursraum-roadmaps.json'),'utf8'));assert.equal(Object.keys(stored.roadmaps).length,1);
 console.log('PASS: electron-store persists roadmap separately from course settings');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(app)await app.close();if(temporary)await fs.rm(temporary,{recursive:true,force:true});});
